### ISSUE TITLE
Avro on textfiles

### ISSUE THREAD

**Issue by chaosmail** [miguno/avro-cli-examples#3]
Thanks for the great examples. I am struggling doing exactly the same using (zipped) csv files (using | as a delimiter), `fromtext` option and a schema file. Could you possibly add an example like this?

I would be willing to contribute if you could guide me to some blog, specification/documentation where I can read about this. Currently I only found [Michael Noll's blog](http://www.michael-noll.com/blog/2013/03/17/reading-and-writing-avro-files-from-the-command-line/#tools-included-in-avro-tools) going into some detail.

Thanks a lot!
Best,
Christoph

**Comment by miguno** [comment]
Is this question is still relevant?
