### ISSUE TITLE
Any idea how to get around the colon bug of avro cli

### ISSUE THREAD

**Issue by George3d6** [miguno/avro-cli-examples#4]
When running avro cli as such:
`
java -jar avro-tools-1.7.7.jar tojson /path/to/my:file.avro`

I get the following error:

`Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI:`

Is there a workaround to this bug other than renaming files ?

**Comment by miguno** [comment]
I am not aware of any workaround other than renaming files.
